### ISSUE TITLE
Reflect#type on instance fails for null field

### ISSUE THREAD

**Issue by PascalSchumacher** [jOOQ/jOOR#37] opened 2017-05-02 13:47 UTC
When using joor 0.9.6, this test:

```java
public static class A {
    String f;
}

@Test
public void test() {
    A a = new A();
    for (Map.Entry<String, Reflect> field : Reflect.on(a).fields().entrySet()) {
        Reflect reflect = field.getValue();
        if (reflect.type() == String.class) {
            System.out.println("Value: " + reflect.get());
        }
    }
}
```
fails with:

```
java.lang.NullPointerException
	at org.joor.Reflect.type(Reflect.java:766)
```

By the way: Thank you very much for providing jOOR! :+1:

**Comment by PascalSchumacher** [comment] 2017-05-02 22:26
No sure this is a bug. Maybe it would be solved by https://github.com/jOOQ/jOOR/issues/33?

**Comment by lukaseder** [comment] 2017-05-03 07:54
Hmm, interesting. Thanks for reporting. I can definitely reproduce this. There's an entire set of use-cases that isn't currently covered and might produce this NPE. This isn't a duplicate of #33, but I definitely think that the `Reflect` instance should keep a reference of the instance *and* type of object for these cases.

Will need to think about this

**Closed** 2017-05-03 08:13 UTC
Labels: P: Medium, R: Fixed, T: Defect
