### ISSUE TITLE
When Reflect.compile(...), if code executed has same ClassName as a previous execution, .class file is never overwritten

### ISSUE THREAD

**Issue by ANLevant** [jOOQ/jOOR#106] opened 2020-08-29 05:01 UTC
### Expected behavior and actual behavior:

**EXPECTED**

```java
//FIRST CALL!!!!
Supplier<String> supplier = Reflect.compile(
    "com.example.HelloWorld",
    "package com.example;\n" +
    "class HelloWorld implements java.util.function.Supplier<String> {\n" +
    "    public String get() {\n" +
    "        return \"Hello World!\";\n" +
    "    }\n" +
    "}\n").create().get();
// Prints "Hello World!"
System.out.println(supplier.get());

//SECOND CALL!
Supplier<String> supplier = Reflect.compile(
    "com.example.HelloWorld",
    "package com.example;\n" +
    "class HelloWorld implements java.util.function.Supplier<String> {\n" +
    "    public String get() {\n" +
    "        return \"ByeBye World!\";\n" +
    "    }\n" +
    "}\n").create().get();

// Prints "ByeBye World!"
System.out.println(supplier.get());
```

**ACTUAL**

```java
//FIRST CALL!!!!
Supplier<String> supplier = Reflect.compile(
    "com.example.HelloWorld",
    "package com.example;\n" +
    "class HelloWorld implements java.util.function.Supplier<String> {\n" +
    "    public String get() {\n" +
    "        return \"Hello World!\";\n" +
    "    }\n" +
    "}\n").create().get();
// Prints "Hello World!"
System.out.println(supplier.get());

//SECOND CALL!
Supplier<String> supplier = Reflect.compile(
    "com.example.HelloWorld",
    "package com.example;\n" +
    "class HelloWorld implements java.util.function.Supplier<String> {\n" +
    "    public String get() {\n" +
    "        return \"ByeBye World!\";\n" +
    "    }\n" +
    "}\n").create().get();

// Prints "Hello World!"
System.out.println(supplier.get());
```

### Steps to reproduce the problem:

1. Make a Reflect.compile(...) call
2. Make another Reflect.compile(...) call with changes on the class code BUT THE SAME CLASS NAME

### Versions:

- jOOR:0.9.12
- Java: 1.8.0_261

**Comment by lukaseder** [comment] 2020-10-13 15:11
Thanks for your request. This is a duplicate of https://github.com/jOOQ/jOOR/issues/72.

I agree we should offer a way to override the default behaviour of using the caller class loader in order to be able to re-define classes compiled with this API.

**Closed by lukaseder** 2020-10-13 15:11 UTC
Labels: P: Medium, T: Enhancement
